

- alias: "thermo_on_1h"
  hide_entity: False
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: "/on 1h"

    - platform: event
      event_type: telegram_callback
      event_data:
        data: "/on 1h"
  
  action:
    - service: automation.trigger
      entity_id: "automation.thermo_on"
    
    - service: timer.start
      entity_id: "timer.thermo_off_1h"


- alias: "thermo on"
  hide_entity: False
  trigger:
    - platform: state
      entity_id: calendar.termostati
      from: "off"
      to: "on"
    
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/on'

    - platform: event
      event_type: telegram_callback
      event_data:
        data: '/on'
  
  condition:
    - condition: state
      entity_id: 'binary_sensor.thermo_season'
      state: 'on'

  action:
    - service: climate.set_temperature
      data:
        temperature: 18.5
    - service: notify.notifier_test
      data:
          message: 'Thermo On'
          data:
              inline_keyboard:
                  - "/off"

- alias: "thermo off"
  hide_entity: False
  trigger:
    - platform: state
      entity_id: calendar.termostati
      from: "on"
      to: "off"
    
    - platform: event
      event_type: telegram_command
      event_data:
        command: "/off"
    
    - platform: event
      event_type: telegram_callback
      event_data:
        data: "/off"
    
    - platform: event
      event_type: timer.finished
      event_data: 
        entity_id: "timer.thermo_off_1h"

  condition:
    - condition: state
      entity_id: 'binary_sensor.thermo_season'
      state: 'on'

  action:
    - service: climate.set_temperature
      data:
        temperature: 13
    - service: notify.notifier_test
      data:
        message: 'Thermo Off'
        data:
            inline_keyboard:
                - "/status"


- alias: "thermo status"
  
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/status'
    
    - platform: event
      event_type: telegram_callback
      event_data:
        data: '/status'
  
  action:
    service: notify.notifier_test
    data:
        message: >
             Giorno: {{states.sensor.temp_giorno.state}} {{states.climate.giorno.state}}
             Notte: {{states.sensor.temp_notte.state}} {{states.climate.notte.state}}
        data:
            inline_keyboard:
                - "/status"
                - "/on,/off" 
                - "/on 1h"

