- alias: "work thermo on mattina"
  hide_entity: True
  trigger:
    platform: time
    at: "05:45:00"
  condition:
        - condition: time
          weekday:
           - mon
           - tue
           - wed
           - thu
           - fri
        - condition: state
          entity_id: 'binary_sensor.thermo_season'
          state: 'on'
                
  action:
    - service: climate.set_temperature
      data:
        temperature: 21

- alias: "work thermo off mattina"
  hide_entity: True
  trigger:
    platform: time
    at: "06:30:00"
  condition:
        - condition: time
          weekday:
           - mon
           - tue
           - wed
           - thu
           - fri
        - condition: state
          entity_id: 'binary_sensor.thermo_season'
          state: 'on'
  action:
    - service: climate.set_temperature
      data:
        temperature: 13

#- alias: "work thermo on pomeriggio"
#  hide_entity: True
#  trigger:
#    platform: time
#    at: "16:00:00"
#  condition:
#        - condition: time
#          weekday:
#           - mon
#           - tue
#           - wed
#           - thu
#           - fri
#        - condition: state
#          entity_id: 'binary_sensor.thermo_season'
#          state: 'on'
#  action:
#    - service: climate.set_temperature
#      data:
#        temperature: 21
#
#
#- alias: "work thermo off pomeriggio"
#  hide_entity: True
#  trigger:
#    platform: time
#    at: "20:30:00"
#  condition:
#        - condition: time
#          weekday:
#           - mon
#           - tue
#           - wed
#           - thu
#           - fri
#        - condition: state
#          entity_id: 'binary_sensor.thermo_season'
#          state: 'on'
#  action:
#    - service: climate.set_temperature
#      data:
#        temperature: 13

