homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  # Impacts weather/sunrise data (altitude above sea level in meters)
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

#zeroconf:

http:
  # Uncomment this to add a password (recommended!)
    api_password: !env_var HA_PASSWORD
    ssl_certificate: !env_var HA_CERT
    ssl_key: !env_var HA_KEY

# Checks for available updates
#updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr


espdiscovery:


mqtt:
    broker: localhost
    port: 1883
    client_id: home-assistant
    keepalive: 60
    protocol: 3.1
    birth_message:
        topic: 'hass/status'
        payload: 'online'
        qos: 1
        retain: true
    will_message:
        topic: 'hass/status'
        payload: 'offline'
        qos: 1
        retain: true

