homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  unit_system: metric
  time_zone: Europe/Rome
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  #  customize: !include customize.yaml


# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

#zeroconf:

http:
 base_url: !secret base_url
 api_password: !secret http_password
 ssl_certificate: !secret ssl_certificate
 ssl_key: !secret privkey
    

# Checks for available updates
#updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
#logbook:

# Track the sun
sun:

# Weather Prediction
#sensor:
#  platform: yr

#google:
#    client_id: !env_var HA_G_CLIENT_ID
#    client_secret: !env_var HA_G_CLIENT_SECRET

espdiscovery:
    sens_to_switch:
        - sensor: "GIORNO"
          switch: "SW_BRD_0"
          switch_nr: "0" 
        - sensor: "NOTTE"
          switch: "SW_BRD_0"
          switch_nr: "1" 


mqtt:
    broker: localhost
    port: 1883
    client_id: home-assistant
    keepalive: 60
    protocol: 3.1
    birth_message:
        topic: 'hass/status'
        payload: 'online'
        qos: 1
        retain: true
    will_message:
        topic: 'hass/status'
        payload: 'offline'
        qos: 1
        retain: true

recorder:
    purge_interval: 1
    purge_keep_days: 5

wake_on_lan:

media_player:
  - platform: "kodi"
    host: "192.168.1.7"
    port: 8080

    turn_on_action:
      - service: "wake_on_lan.send_magic_packet"
        data:
            mac: !secret kodi_mac 
            broadcast_address: "192.168.1.255"
    
    turn_off_action:
      service: "media_player.kodi_call_method"
      data:
        entity_id: "media_player.kodi"
        method: "System.Shutdown"


group:
    default_view:
        view: yes
        icon: mdi:home 
        entities:
            - group.climate
            - group.temperature
            - group.humidity
            - group.thermosw
            - group.thermo

    media:
        name: Media
        view: yes
        entities:
          - "media_player.kodi"

automation: !include automation.yaml
 
