homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  # Impacts weather/sunrise data (altitude above sea level in meters)
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  #  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

#zeroconf:

http:
 base_url: pupillo.duckdns.org:8123
 api_password: !secret http_password
 ssl_certificate: /config/cert.pem
 ssl_key: /config/privkey.pem

# Checks for available updates
#updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
#logbook:

# Track the sun
sun:

# Weather Prediction
#sensor:
#  platform: yr

#google:
#    client_id: !env_var HA_G_CLIENT_ID
#    client_secret: !env_var HA_G_CLIENT_SECRET

espdiscovery:
    sens_to_switch:
        - sensor: "GIORNO"
          switch: "SW_BRD_0"
          switch_nr: "0" 
        - sensor: "NOTTE"
          switch: "SW_BRD_0"
          switch_nr: "1" 


mqtt:
    broker: localhost
    port: 1883
    client_id: home-assistant
    keepalive: 60
    protocol: 3.1
    birth_message:
        topic: 'hass/status'
        payload: 'online'
        qos: 1
        retain: true
    will_message:
        topic: 'hass/status'
        payload: 'offline'
        qos: 1
        retain: true


recorder:
    purge_interval: 1
    purge_keep_days: 5

 
automation:
- alias: "work thermo on mattina"
  hide_entity: True
  trigger:
    platform: time
    at: "06:00:00"
  condition:
    condition: time
    weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: climate.set_temperature
      data:
        temperature: 21

- alias: "work thermo off mattina"
  hide_entity: True
  trigger:
    platform: time
    at: "07:30:00"
  condition:
    condition: time
    weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: climate.set_temperature
      data:
        temperature: 13

- alias: "work thermo on pomeriggio"
  hide_entity: True
  trigger:
    platform: time
    at: "16:00:00"
  condition:
    condition: time
    weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: climate.set_temperature
      data:
        temperature: 21


- alias: "work thermo off pomeriggio"
  hide_entity: True
  trigger:
    platform: time
    at: "20:30:00"
  condition:
    condition: time
    weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: climate.set_temperature
      data:
        temperature: 13

